//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaKiller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaKiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [red]DEBUG[/] mode enabled. 的本地化字符串。
        /// </summary>
        internal static string DebugModeEnabled {
            get {
                return ResourceManager.GetString("DebugModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [red]Mission(s) cancelled forcely.[/] 的本地化字符串。
        /// </summary>
        internal static string ErrMissionsForcelyCancelled {
            get {
                return ResourceManager.GetString("ErrMissionsForcelyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;END&gt; 的本地化字符串。
        /// </summary>
        internal static string ErrorReportEnd {
            get {
                return ResourceManager.GetString("ErrorReportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Report 的本地化字符串。
        /// </summary>
        internal static string ErrorReportTitle {
            get {
                return ResourceManager.GetString("ErrorReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [red]Force Overwrite[/] mode enabled. Overwriting settings in any preset will be ignored. 的本地化字符串。
        /// </summary>
        internal static string ForceOverwriteEnabled {
            get {
                return ResourceManager.GetString("ForceOverwriteEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaKiller started. :) 的本地化字符串。
        /// </summary>
        internal static string MainProcessStarted {
            get {
                return ResourceManager.GetString("MainProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caches for all media informations are cleared. 的本地化字符串。
        /// </summary>
        internal static string MediaInfoCachesCleared {
            get {
                return ResourceManager.GetString("MediaInfoCachesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [green]No Overwrite[/] mode enabled. No files will be overwritten. You are safe. 的本地化字符串。
        /// </summary>
        internal static string NoOverwriteEnabled {
            get {
                return ResourceManager.GetString("NoOverwriteEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [grey][red]Not all[/] missions are successfully finished. Append [yellow]-n[/] option to [yellow]same options[/] and run MediaKiller again to [green] skip finished missions[/].[/] 的本地化字符串。
        /// </summary>
        internal static string NoteForNextTime {
            get {
                return ResourceManager.GetString("NoteForNextTime", resourceCulture);
            }
        }
    }
}
